#!/bin/bash

#lib-info: helps building the presentation index

source "$TERMINAL_APP_LIB_PATH/color"

function index_file_write_entry {
  __depth=$1
  __file="$2"
  __name="$3"
  __path="$4"

  printf '%*s - [%s](%s) \n' $__depth ' ' "$__name" "$__path" >> "$__file"
}

function index_file_init {
  __index_file="$1"
  __headline="$2"

  file_clear "$__index_file"

  file_append "$__index_file" "# $__headline"

  file_append_newline "$__index_file"
}

function index_path_to_name {
  __path="$1"

  __path="${__path:3}" # cut of number and whitespace

  __path=$(echo "$__path" | sed 's/[0-9]\{2\}_/ => /g')
  __path=$(echo "$__path" | tr '_-' ' ') # eleminate _ and -
  __path=$(echo "$__path" | tr '/' ' - ') # replace /

  __path=${__path/.md/ } # strip .md ending

  # uc first all words
  __path=$(awk '{for(i=0;++i<=NF;){OFS=(i==NF)?RS:FS;printf toupper(substr($i,0,1)) substr($i,2) OFS }}' <<< "$__path")

  echo "$__path"
}
