#!/bin/bash

#command-info: build index for the easy-presenter

source "$TERMINAL_PATH/app.bootstrap"

repository_index_file="$1"
depth=0

for language in "$INDEX_SUPPORTED_LANGS"
do

  possible_lang_folder="$TERMINAL_PATH/$language"

  orange "checking $possible_lang_folder for existence"

  # check if for given language a presentation repository exists
  if [ -d "$possible_lang_folder" ];
  then
    $(index_file_write_entry 0 "$repository_index_file" "$language/README.md" "$language")

    index_file="$possible_lang_folder/README.md"

    file_clear "$index_file"

    if [ -f "$possible_lang_folder/teaser.md" ];
    then
      file_append "$index_file" "$(cat "$possible_lang_folder/teaser.md")"
    fi

    orange "building: $language -> $index_file"

    command_exec '_build-index-for-folder' "$possible_lang_folder" "$index_file" $depth
  fi

done
