#!/bin/bash

#command-info: private

source "$TERMINAL_PATH/app.bootstrap"

source_folder="$1"
parent_folder="$2"
index_file_pages="$3"
depth=$4

cd "$source_folder"

# find all folders and md files
find -s . \( -name "*.md" -o -type d \) -maxdepth 1 -print0 |
    while IFS= read -r -d $'\0' folder; do

      folder=${folder:2} # strip leading ./
      path_absolute="$source_folder/$folder"
      path_relative="$parent_folder/$folder"

      # exclude README.md, assets/, teaser.md, ./
      if [ "$folder" == 'README.md' ] || [ "$folder" == 'index.md' ] || [ "$folder" == 'assets' ] || [ "x$folder" == "x" ];
      then
        continue
      fi

      if [ -d "$path_absolute" ]; # if directory
      then
          entry_name=index_name_from_path_or_page "$path_absolute"

          $(index_file_write "$index_file_pages" $depth "$entry_name" "$path_relative")

          command_exec '_build-index-for-folder' "$source_folder" "$parent_folder" "$index_file_pages" `expr $depth + 4`

          file_append_newline "$index_file_pages"

      else # if file
          entry_name=index_name_from_page "$path_absolute"

          $(index_file_write "$index_file_pages" $depth "$link_name" "$path_relative" )
      fi

    done

cd -
