#!/bin/bash

#command-info: build index for the easy-presenter

source "$TERMINAL_PATH/app.bootstrap"

index_file_language="$EASY_PRESENTER_SOURCE/README.md"
parent_folder=''
depth=0

file_clear "$index_file_language"

index_file_init "$index_file_language" "Available languages:"

for language_path in "$EASY_PRESENTER_SOURCE"/*
do
  language_path_absolute="$EASY_PRESENTER_SOURCE/$language_path"

  # if it is a file
  if [ -f "$language_path" ];
  then
    continue
  fi

  language=$(basename "$language_path")

  # write language index file
  file_append "$index_file_language" "  - [$language](./$language)"

  index_file_pages="$language_path/index.md"

  # command_exec '_build-index-for-folder' "$language_path" "$index_file_pages" "$parent_folder" $depth
done
