#!/bin/bash

#lib-info: helps building the presentation index

source "$TERMINAL_APP_LIB_PATH/color"

# function index_write_entry {
function index_file_write_entry {
  name="$1"
  path="$2"
  file="$3"
  depth=$4

  printf '%*s - [%s](%s) \n' $depth ' ' "$name" "$path" >> "$file"
}

# function index_write {
function index_file_write {
  input="$1"
  index_file="$2"

  echo "$input" >> "$index_file"
}

#function index_newline {
function index_file_write_newline {
  index_file="$1"

  echo '' >> "$index_file"
}

#function index_reset_file {
function index_file_reset {
  index_file="$1"

  > "$index_file"
}

function index_file_init {
  headline="$1"
  index_file="$2"

  index_file_reset "$index_file"

  index_file_write "# $repository_name" "$index_file"

  index_file_write_newline "$index_file"

}

function index_path_to_name {
  path="$1"

  path="${path:3}" # cut of number and whitespace

  path=$(echo "$path" | tr '_-/' ' ') # eleminate _

  path=${path/.md/ } # strip .md ending

  # uc first all words
  path=$(awk '{for(i=0;++i<=NF;){OFS=(i==NF)?RS:FS;printf toupper(substr($i,0,1)) substr($i,2) OFS }}' <<< "$path")

  echo "$path"
}
