#!/bin/bash

#command-info: build index for the easy-presenter

source bootstrap

repository_index_file="$TERMINAL_PATH/index"
> "$repository_index_file"

for language in "$INDEX_SUPPORTED_LANGS"
do
  possible_lang_folder="$TERMINAL_PATH/$language"
  orange "checking $possible_lang_folder for existence"
  if [ -d "$possible_lang_folder" ];
  then
    echo "$language/README.md" >> "$repository_index_file"

    index_file="$possible_lang_folder/index"

    orange "building: $language -> $index_file"

    command_exec 'build-index-for-language' $possible_lang_folder $index_file
  fi
done
