#!/bin/bash

#command-info: build index for the easy-presenter

source $TERMINAL_PATH/bootstrap

repository_index_file="$TERMINAL_PATH/README.md"

> "$repository_index_file"

for language in "$INDEX_SUPPORTED_LANGS"
do

  possible_lang_folder="$TERMINAL_PATH/$language"

  orange "checking $possible_lang_folder for existence"

  if [ -d "$possible_lang_folder" ];
  then
    index_write_entry "$language" "$language/README.md" "$repository_index_file" 0

    index_file="$possible_lang_folder/README.md"

    rm -f "$index_file"

    orange "building: $language -> $index_file"

    command_exec 'build-index-for-folder' "$possible_lang_folder" "$index_file" 0 "$language"
  fi

done
