#!/bin/bash

#command-info: private

source $TERMINAL_PATH/app.bootstrap

source_folder="$1"
repository_index_file="$2"
depth=$3
parent_folder="$4"

if [ $depth -gt 0 ];
then
  folder_index_file="$source_folder/README.md"
  subfolder_name=$(index_path_to_name "$parent_folder")
  index_file_init "$subfolder_name" "$folder_index_file"
fi

cd "$source_folder"

# find all folders and md files
find -s . \( -name "*.md" -o -type d \) -maxdepth 1 -print0 |
    while IFS= read -r -d $'\0' folder; do

      # exclude ./
      if [ ${#folder} -le 3 ];
      then
        continue
      fi

      folder=${folder:2} # strip leading ./

      # exclude de/README.md
      if [ "$folder" == "README.md" ];
      then
        continue
      fi

      path_absolute="$source_folder/$folder"
      relative_path="$parent_folder$folder"

      if [ -d "$path_absolute" ]; # if directory
      then
          path_name=$(index_path_to_name "$folder")

          $(index_file_write_entry "$path_name" "$relative_path" "$repository_index_file" $depth)

          command_exec 'build-index-for-folder' "$path_absolute" "$repository_index_file" `expr $depth + 4` "$relative_path/"

          index_file_write_newline "$repository_index_file"

          if [ $depth -gt 0 ];
          then
            $(index_file_write_entry "$path_name" "$relative_path" "$folder_index_file" 0)
            index_file_write_newline "$folder_index_file"
          fi
      else # if file
          link_name=$(cat "$path_absolute" | grep "# ")

          if [ ${#link_name} -ge 3 ];
          then
            link_name=${link_name:2}
          else
            link_name=$(index_path_to_name "$folder")
          fi

          $(index_file_write_entry "$link_name" "$relative_path" "$repository_index_file" $depth)
          $(index_file_write_entry "$link_name" "$relative_path" "$folder_index_file" 0)
      fi

    done

cd -
