#!/bin/bash

#command-info: build index for the easy-presenter

source "$TERMINAL_PATH/app.bootstrap"

repository_index_file="$TERMINAL_PATH/README.md"

# write language index header
index_file_init "$repository_index_file" "$repository_name"

file_append "$repository_index_file" "### Langauges:"

file_append_newline "$repository_index_file"

# build inside language folder
command_exec '_build-toplevel-folder' "$repository_index_file"
