#!/bin/bash

#command-info: build index for the easy-presenter

source $TERMINAL_PATH/bootstrap

source_folder="$1"
index_file="$2"
depth=$3

echo "$prefix_string"

cd "$source_folder"

find -s . \( -name "*.md" -o -type d \) -maxdepth 1 -print0 |
    while IFS= read -r -d $'\0' line; do

      if [ ${#line} -le 2 ];
      then
        continue
      fi

      full_file="$source_folder/$line"
      line=${line:2}

      if [ -d "$full_file" ];
      then
          # directory
          printf '%*s - [%s/](%s/) \n' $depth ' ' "$line" "$line" >> "$index_file"

          command_exec 'build-index-for-folder' "$full_file" "$index_file" `expr $depth + 4`

          echo '' >> "$index_file"
      else
          # file
          link_name=$(cat "$full_file" | grep "# ")

          if [ ${#link_name} -ge 3 ];
          then
            link_name=${link_name:2}
          else
            link_name="$line"
          fi

          printf '%*s - [%s](%s) \n' $depth ' ' "$link_name" "$line" >> "$index_file"
      fi

    done

cd -
