#!/bin/bash

#command-info: private

source $TERMINAL_PATH/app.bootstrap

source_folder="$1"
folder_index_file="$2"
depth=$3
parent_folder="$4"

cd "$source_folder"

# find all folders and md files
find -s . \( -name "*.md" -o -type d \) -maxdepth 1 -print0 |
    while IFS= read -r -d $'\0' folder; do

      # exclude ./
      if [ ${#folder} -le 2 ];
      then
        continue
      fi

      folder=${folder:2} # strip leading ./

      # exclude de/README.md
      if [ "$folder" == "README.md" ];
      then
        continue
      fi

      path_absolute="$source_folder/$folder"
      relative_path="$parent_folder$folder"

      if [ -d "$path_absolute" ]; # if directory
      then
          path_name=$(index_path_to_name "$folder")

          index_write_entry "$path_name" "$relative_path" "$folder_index_file" $depth

          command_exec 'build-index-for-folder' "$path_absolute" "$folder_index_file" `expr $depth + 4` "$relative_path/"

          index_newline "$folder_index_file"

      else # if file
          link_name=$(cat "$path_absolute" | grep "# ")

          if [ ${#link_name} -ge 3 ];
          then
            link_name=${link_name:2}
          else
            link_name=$(index_path_to_name "$folder")
          fi

          index_write_entry "$link_name" "$relative_path" "$folder_index_file" $depth
      fi

    done

cd -
